---
title: "BeeSearch Collection Effort"
author: "Dr. Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = F,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



## Overview

This analysis creates Figure S1. Collecting effort across years at all sites. a) Trap days expressed as a standard trap set over a 24-hour period. (BPF figures expressed as equivalents with reference to numbers of specimens collected by standard trap sets at other sites.) b) Net collecting events.


```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Load Packages
library(tidyverse) # Needed for data wrangling: dplyr, tidyr, ggplot2
library(cowplot) # Needed for publication-quality ggplots


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
dat1 <- read.csv("data/collection_effort.csv")

dat2 <- read.csv("data/CABS1.csv")
```

```{r data_wrangling, echo = F}


dat1 <- dat1 %>% 
  mutate(across(c(Year, Collection_method), factor),
         across(c(BPF : Total), as.numeric)) %>% 
  pivot_longer(cols = c(BPF : Total), names_to = "Site")



```

```{r collection_figure, echo = F, fig.width = 6}
level_order <- c("BPF", "SCL", "POS", "Total")
facet_order <- c("Trap", "Net")

A <- dat1 %>%
  filter(Collection_method == "Trap") %>% 
  ggplot(aes(Year, y = value,
             fill = factor(Site, level = level_order))) +
  geom_col(width = .6, position = position_dodge(0.6),
           show.legend = F) +
  scale_fill_manual(values = c("#009E73", "#56B4E9",
                               "#E69F00", "maroon4"),
                    label = c("BPF", "SCL",
                              "POS", "All Sites")) +
  theme_cowplot() +
  theme(legend.title = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "bottom") +
  labs(y = "Trap days")

B <- dat1 %>%
  filter(Collection_method != "Trap") %>% 
  ggplot(aes(Year, y = value,
             fill = factor(Site, level = level_order))) +
  geom_col(width = .6, position = position_dodge(0.6)) +
  scale_fill_manual(values = c("#009E73", "#56B4E9",
                               "#E69F00", "maroon4"),
                    label = c("BPF", "SCL",
                              "POS", "All Sites")) +
  scale_y_continuous(limits = c(0, 80)) +
  theme_cowplot() +
  theme(legend.title = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.justification = "center",
        legend.key.spacing.x = unit(1.5, "cm"),
        legend.key.width = unit(.7, "cm"),
        legend.key.height = unit(.3, "cm")) +
  labs(y = "Net events")


plot_grid(A, B, align = "h", nrow = 2, labels = c("A", "B"))
```


## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


