---
title: "BeeSearch genus plots"
author: "Dr. Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = F,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



## Overview

This analysis plots the count of unique species/genus and the proportional abundance of each genus.




```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Load Packages
library(tidyverse) # Needed for data wrangling: dplyr, tidyr, ggplot2
library(cowplot) # Needed for publication-quality ggplots
library(knitr)



# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
dat1 <- read.csv("data/CABS1.csv")

comp.sites <- read.csv("data/comparable.sites.csv")

site.locs <- read.csv("data/site.locations.csv")


####################################

```


```{r Data_Wrangling, echo = F, comment = ""}

# general cleaning and conversion:
dat1 <- dat1 %>% 
  uncount(Count) %>% 
  mutate(across(c(Station : Sex, Site), as.factor), # convert to factors
         Date = ymd(Label.Date), # Convert to date
         Year = year(Date), # Create year column
         Month = month(Date), # create month column
         # JD --- Day of year (julian day)
         JD = yday(Date),
         # ToY --- Time of Year
         ToY = case_when(JD < 135 ~ "early",
                         JD > 205 ~ "late",
                         TRUE ~ "mid"),
         # Create a station/year column for grouping
         StationYear = paste(Station, Year, sep = "_")) %>% 
  filter(Station != "",
         Site != "") %>% # remove empty station & site records
  # convert M/F to male/female to avoid "F = FALSE" misinterpretation
  mutate(Sex = case_when(
      Sex == "M" ~ "male",
      Sex == "F" ~ "female",
      TRUE ~ NA_character_ # Handle any unexpected values
    )) %>% 
  # correct misidentification record
  mutate(Short.label.name = case_when(
    Short.label.name == "Megachile apicalis" ~ "Megachile rotundata",
    TRUE ~ as.character(Short.label.name)
  )) %>% 
  # correct misindentification sex classification
  mutate(Sex = case_when(
    Unique.Specimen.Number == 678 |
      Unique.Specimen.Number == 679 ~ "Male",
    TRUE ~ as.character(Sex)
  ))


# Create data with all the incompatible sites (unequal sampling effort)
incomp.sites <- dat1 %>% 
  select(StationYear) %>% 
  filter(StationYear == "POS1_2018" |
           StationYear == "POS10_2019" |
           StationYear == "POS11_2018" |
           StationYear == "POS13_2017" |
           StationYear == "POS14_2017" |
           StationYear == "POS15_2017" |
           StationYear == "POS16_2017" |
           StationYear == "POS17_2017" |
           StationYear == "POS18_2017" |
           StationYear == "POS19_2017" |
           StationYear == "POS20_2017" |
           StationYear == "POS20_2019" |
           StationYear == "POS21_2017" |
           StationYear == "POS22_2019" |
           StationYear == "POS23_2019" |
           StationYear == "POS1_2014" |
           StationYear == "POS2_2014" |
           StationYear == "POS3_2014") %>% 
  distinct() %>% 
  mutate(StationYear = factor(StationYear))


# filter out the sites with incompatible sampling effort
dat2 <- anti_join(dat1, incomp.sites, by = "StationYear") %>% 
  # unequal sampling in 2020
  filter(Year != 2020) %>% 
  mutate(Year = factor(Year)) %>% 
  droplevels()

# keep the single record of morphospecies "Hylaeus sp. 2023_1"
keep.Hylaeus <- dat2 %>% 
  filter(str_detect(Short.label.name, "Hylaeus sp. 2023"))

# remove any records where species is undetermined:
dat2 <- dat2 %>% 
  filter(!str_detect(Short.label.name, "(?<!m)sp\\.")) %>% 
  bind_rows(keep.Hylaeus)
# ^^^ this data will be used when analyses do not depend on number of species


# Filter out certain morphospecies that could inflate richness
dat.ex.msp <- dat2 %>% 
  filter(!(Sex == "male" & str_detect(Short.label.name,
                                    "Sphecodes msp\\.")),
         !(Sex == "female" & str_detect(Short.label.name,
                                       "Osmia msp\\.")),
         !(Sex == "female" & str_detect(Short.label.name,
                                        "Nomada msp\\.")))
# ^^^ this data will be used for analyses involving species counts


```

# Descriptive measures of genera

## All sites together
```{r genera_figs_all_sites, echo = F}

genus.counts <- dat.ex.msp %>% 
  select(Genus, Short.label.name) %>% 
  group_by(Genus) %>% 
  distinct() %>% 
  tally(name = "Species")

genus.props <- dat.ex.msp %>% 
  group_by(Genus) %>% 
  tally(name = "Prop") %>% 
  mutate(prop.abund = Prop/nrow(dat.ex.msp))

genus <- left_join(genus.counts, genus.props, by = "Genus")

###################
# color palette
c24 <- c(
  "maroon", "#E31A1C", "green4", "#6A3D9A",
  "#FF7F00", "gold1", "mediumpurple1","skyblue2", "#FB9A99",
  "palegreen2", "#CAB2D6", "#FDBF6F", "gray70", "khaki2",
  "dodgerblue2", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3", "darkorange4"
)


genus_levels <- levels(genus$Genus)

color_mapping <- setNames(c24, genus_levels)



##########
genus %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "Genus",
       y = "") +
  annotate(geom = "text",
           x = 5,
           y = -30, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 5,
           y = 18, 
           label = "No. unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)

#################################################
genus_plot_all <- genus %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "",
       y = "") +
  annotate(geom = "text",
           x = 5,
           y = -30, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 5,
           y = 18, 
           label = "Unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)

```

## POS
```{r genera_figs_pos, echo = F}

genus.counts.pos <- dat.ex.msp %>% 
  filter(Site == "POS") %>% 
  select(Genus, Short.label.name) %>% 
  group_by(Genus) %>% 
  distinct() %>% 
  tally(name = "Species")

genus.props.pos <- dat.ex.msp %>% 
  filter(Site == "POS") %>% 
  group_by(Genus) %>% 
  tally(name = "Prop") %>% 
  mutate(prop.abund = Prop/nrow(filter(dat.ex.msp, Site == "POS")))

genus.pos <- left_join(genus.counts.pos, genus.props.pos, by = "Genus")

genus.pos %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "Genus",
       y = "") +
  annotate(geom = "text",
           x = 5,
           y = -30, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 5,
           y = 13, 
           label = "No. unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)
#################################################
genus_plot_pos <- genus.pos %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  scale_x_discrete(position = "top") +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "",
       y = "") +
  annotate(geom = "text",
           x = 5,
           y = -30, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 5,
           y = 13, 
           label = "Unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)

```

## SCL
```{r genera_figs_scl, echo = F}

genus.counts.scl <- dat.ex.msp %>% 
  filter(Site == "SCL") %>% 
  select(Genus, Short.label.name) %>% 
  group_by(Genus) %>% 
  distinct() %>% 
  tally(name = "Species")

genus.props.scl <- dat.ex.msp %>% 
  filter(Site == "SCL") %>% 
  group_by(Genus) %>% 
  tally(name = "Prop") %>% 
  mutate(prop.abund = Prop/nrow(filter(dat.ex.msp, Site == "SCL")))

genus.scl <- left_join(genus.counts.scl, genus.props.scl, by = "Genus")

genus.scl %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "Genus",
       y = "") +
  annotate(geom = "text",
           x = 5,
           y = -15, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 5,
           y = 10, 
           label = "No. unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)
###################################################
genus_plot_scl <- genus.scl %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "",
       y = "") +
  annotate(geom = "text",
           x = 5,
           y = -15, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 5,
           y = 10, 
           label = "Unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)

```

## BPF
```{r genera_figs_bpf, echo = F}

genus.counts.bpf <- dat.ex.msp %>% 
  filter(Site == "BPF") %>% 
  select(Genus, Short.label.name) %>% 
  group_by(Genus) %>% 
  distinct() %>% 
  tally(name = "Species")

genus.props.bpf <- dat.ex.msp %>% 
  filter(Site == "BPF") %>% 
  group_by(Genus) %>% 
  tally(name = "Prop") %>% 
  mutate(prop.abund = Prop/nrow(filter(dat.ex.msp, Site == "BPF")))

genus.bpf <- left_join(genus.counts.bpf, genus.props.bpf, by = "Genus")



genus.bpf %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  scale_x_discrete(position = "top") +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "",
       y = "") +
  annotate(geom = "text",
           x = 5,
           y = -20, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 5,
           y = 12, 
           label = "No. unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)


#########################################################
genus_plot_bpf <- genus.bpf %>% 
  ggplot(aes(x = fct_reorder(Genus, Species, .desc = F),
             y = Species, fill = Genus)) +
  geom_col(show.legend = F) +
  geom_col(aes(y = -prop.abund * 100, fill = Genus),
           show.legend = F) +
  geom_hline(yintercept = 0) +
  scale_x_discrete(position = "top") +
  coord_flip() +
  theme_cowplot(font_size = 16) +
  labs(x = "",
       y = "") +
  annotate(geom = "text",
           x = 4.5,
           y = -20, 
           label = "Proportional\nabundance (%)",
           color = "black",
           size = 5) +
  annotate(geom = "text",
           x = 4.4,
           y = 12, 
           label = "Unique\nspecies",
           color = "black",
           size = 5) +
  scale_y_continuous(labels = function(y) abs(y)) +
  scale_fill_manual(values = color_mapping)

```

## All genus plots together in one figure:
```{r genus_plot_one_fig, echo = F, fig.width=10, fig.height=10}

plot_grid(genus_plot_all, genus_plot_pos,
          genus_plot_scl, genus_plot_bpf, 
          labels = c("A", "B", "C", "D"),
          label_size = 14)

```



## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


