---
title: "BeeSearch Pie Plots"
author: "Dr. Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = F,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



## Overview

This analysis creates pie charts for 1) species richness per family, 2) individuals collected per family, and 3) genera per family.




```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Load Packages
library(tidyverse) # Needed for data wrangling: dplyr, tidyr, ggplot2
library(cowplot) # Needed for publication-quality ggplots
library(knitr)



# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
dat1 <- read.csv("data/CABS1.csv")

####################################

```


```{r Data_Wrangling, echo = F, comment = ""}


dat1 <- dat1 %>% 
  uncount(Count) %>% 
  mutate(across(c(Station : Sex, Site), as.factor), # convert to factors
         Date = ymd(Label.Date), # Convert to date
         Year = year(Date), # Create year column
         Month = month(Date), # create month column
         # JD --- Day of year (julian day)
         JD = yday(Date),
         # ToY --- Time of Year
         ToY = case_when(JD < 135 ~ "early",
                         JD > 205 ~ "late",
                         TRUE ~ "mid"),
         # Create a station/year column for grouping
         StationYear = paste(Station, Year, sep = "_")) %>% 
  filter(Station != "",
         Site != "") %>% # remove empty station & site records
  # convert M/F to male/female to avoid "F = FALSE" misinterpretation
  mutate(Sex = case_when(
      Sex == "M" ~ "male",
      Sex == "F" ~ "female",
      TRUE ~ NA_character_ # Handle any unexpected values
    )) %>% 
  # correct misidentification record
  mutate(Short.label.name = case_when(
    Short.label.name == "Megachile apicalis" ~ "Megachile rotundata",
    TRUE ~ as.character(Short.label.name)
  )) %>% 
  # correct misindentification sex classification
  mutate(Sex = factor(case_when(
    Unique.Specimen.Number == 678 |
      Unique.Specimen.Number == 679 ~ "male",
    TRUE ~ as.character(Sex)
  )))



#############################################

genus.counts <- dat1 %>% 
  select(Genus, Short.label.name) %>% 
  group_by(Genus) %>% 
  distinct() %>% 
  tally(name = "Species")

genus.props <- dat1 %>% 
  group_by(Genus) %>% 
  tally(name = "Prop") %>% 
  mutate(prop.abund = Prop/nrow(dat1))

genus <- left_join(genus.counts, genus.props, by = "Genus")



genus <- genus %>% 
  mutate(family = factor(c(
    "Halictidae", "Andrenidae", "Megachilidae", "Apidae",
    "Apidae", "Apidae", "Apidae", "Megachilidae", "Colletidae",
    "Apidae", "Apidae", "Halictidae", "Megachilidae", "Megachilidae",
    "Colletidae", "Halictidae", "Megachilidae", "Apidae", "Apidae",
    "Megachilidae", "Andrenidae", "Halictidae", "Megachilidae",
    "Apidae"
  )))




# color palette
c5 <- c(
  "maroon", "#FF7F00", "mediumpurple1",
  "steelblue4", "darkturquoise"
)


family_levels <- levels(genus$family)

color_mapping <- setNames(c5, family_levels)



```


# Species richness per family

### As percentages:
```{r species_rich_per_family_percents, echo = F}

genus %>% 
  group_by(family) %>% 
  summarise(spp_rich = sum(Species)) %>% 
  arrange(desc(family)) %>% 
  mutate(prop = round(spp_rich / sum(.$spp_rich) * 100, 1),
         ypos = cumsum(prop) - 0.5 * prop) %>% 
  ggplot(aes(x = "", y = prop, fill = family)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  geom_text(aes(y = ypos, label = prop),
            color = "white", size = 6) +
  scale_fill_brewer(palette="Set1") +
  labs(fill = "Family") +
  scale_fill_manual(values = color_mapping) +
  theme(legend.text = element_text(size = 16),
        legend.title = element_text(size = 18))



```


### As counts:
```{r spp_rich_per_family_counts, echo = F}

genus %>% 
  group_by(family) %>% 
  summarise(spp_rich = sum(Species)) %>% 
  arrange(desc(family)) %>% 
  mutate(prop = spp_rich / sum(.$spp_rich) * 100,
         ypos = cumsum(prop) - 0.5 * prop) %>% 
  ggplot(aes(x = "", y = prop, fill = family)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  geom_text(aes(y = ypos, label = spp_rich),
            color = "white", size = 6) +
  scale_fill_brewer(palette="Set1") +
  labs(fill = "Family") +
  scale_fill_manual(values = color_mapping) +
  theme(legend.text = element_text(size = 16),
        legend.title = element_text(size = 18))

```

# Individuals collected per family

### As percentages:
```{r specimens_per_family_percents, echo = F}

genus %>% 
  group_by(family) %>% 
  summarise(specimens = sum(Prop)) %>% 
  arrange(desc(family)) %>% 
  mutate(prop = round(specimens / sum(.$specimens) * 100, 1),
         ypos = cumsum(prop) - 0.5 * prop) %>% 
  ggplot(aes(x = "", y = prop, fill = family)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggrepel::geom_text_repel(aes(y = ypos, label = prop),
            color = "white", size = 6) +
  scale_fill_brewer(palette="Set1") +
  labs(fill = "Family") +
  scale_fill_manual(values = color_mapping) +
  theme(legend.text = element_text(size = 16),
        legend.title = element_text(size = 18))

```


### As counts:
```{r specimens_per_family_counts, echo = F}

genus %>% 
  group_by(family) %>% 
  summarise(specimens = sum(Prop)) %>% 
  arrange(desc(family)) %>% 
  mutate(prop = specimens / sum(.$specimens) * 100,
         ypos = cumsum(prop) - 0.5 * prop) %>% 
  ggplot(aes(x = "", y = prop, fill = family)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  ggrepel::geom_text_repel(aes(y = ypos, label = specimens),
            color = "white", size = 6) +
  scale_fill_brewer(palette="Set1") +
  labs(fill = "Family") +
  scale_fill_manual(values = color_mapping) +
  theme(legend.text = element_text(size = 16),
        legend.title = element_text(size = 18))

```

# Genera per family

### As percentages:
```{r genera_per_family_percents, echo = F}

genus %>% 
  group_by(family, Genus) %>% tally() %>% 
  group_by(family) %>% tally() %>% 
  arrange(desc(family)) %>% 
  mutate(prop = round(n / sum(.$n) * 100, 1),
         ypos = cumsum(prop) - 0.5 * prop) %>% 
  ggplot(aes(x = "", y = prop, fill = family)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  geom_text(aes(y = ypos, label = prop),
            color = "white", size = 6) +
  scale_fill_brewer(palette="Set1") +
  labs(fill = "Family") +
  scale_fill_manual(values = color_mapping) +
  theme(legend.text = element_text(size = 16),
        legend.title = element_text(size = 18))

```


### As counts:
```{r genera_per_family_counts, echo = F}

genus %>% 
  group_by(family, Genus) %>% tally() %>% 
  group_by(family) %>% tally() %>% 
  arrange(desc(family)) %>% 
  mutate(prop = n / sum(.$n) * 100,
         ypos = cumsum(prop) - 0.5 * prop) %>% 
  ggplot(aes(x = "", y = prop, fill = family)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void() +
  geom_text(aes(y = ypos, label = n),
            color = "white", size = 6) +
  scale_fill_brewer(palette="Set1") +
  labs(fill = "Family") +
  scale_fill_manual(values = color_mapping) +
  theme(legend.text = element_text(size = 16),
        legend.title = element_text(size = 18))

```


## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


